### ISSUE TITLE
Format to set the expiry of the cookies

### ISSUE THREAD

**Issue by MeRahulAhire** [voltace/browser-cookies#25]
I want to use this library in project but had an doubt regarding setting [expiry for the token](https://www.npmjs.com/package/browser-cookies#options). Does this library support the [ms](https://www.npmjs.com/package/ms) library format as below?

```
ms('2 days')  // 172800000
ms('1d')      // 86400000
ms('10h')     // 36000000
ms('2.5 hrs') // 9000000
ms('2h')      // 7200000
ms('1m')      // 60000
ms('5s')      // 5000
ms('1y')      // 31557600000
ms('100')     // 100
ms('-3 days') // -259200000
ms('-1h')     // -3600000
ms('-200')    // -200
```
or do I need to use it additionally?

**Comment by hyrious** [comment]
No, there's no built-in support for ms. https://github.com/voltace/browser-cookies/blob/f7de017e295b89241e14d047c2f98f2b69a510c7/src/browser-cookies.js#L18-L23
You can pass a number in days, or any other arguments that `new Date()` can read. For example:
```js
cookies.set('count', 42, {expires: (new Date().getTime() + ms('1d')) / 864e5});
```
